[project]
name = "nfctester"
version = "0.0.35"
description = "A RFID/NFC automation testing framework for cards and readers."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "loguru>=0.7.3",
    "pycryptodome>=3.23.0",
    "pyserial>=3.5",
]

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
nfctester = "nfctester.main:main"
pn532-scanner = "nfctester.tools.pn532_scanner:run_scanner"
aes128-cli = "nfctester.tools.aes128_cli:main"



[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]

[tool.uv]
package = true

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "pytest-dependency>=0.6.0"
]


[tool.bumpversion]
current_version = "0.0.35"
commit = true
tag = true
allow_dirty = true
tag_name = "v{new_version}"
message = "chore(release): bump version {current_version} → {new_version}"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]

[[tool.bumpversion.files]]
filename = "pyproject.toml"

[[tool.bumpversion.files]]
filename = "README.md"
search = "version-{current_version}-green.svg"
replace = "version-{new_version}-green.svg"
