[project]
name = "CarrotRFIDTester"
version = "0.0.32"
description = "A RFID/NFC automation testing framework for cards and readers."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "loguru>=0.7.3",
    "pycryptodome>=3.23.0",
    "pyserial>=3.5",
]

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
crft = "crft.main:main"
pn532-scanner = "crft.tools.pn532_scanner:run_scanner"
aes128-cli = "crft.tools.aes128_cli:main"



[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]

[tool.uv]
package = true

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]


[tool.bumpversion]
current_version = "0.0.32"
allow_dirty = true
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

[[tool.bumpversion.files]]
filename = "pyproject.toml"

# 驱动文件版本号
# [[tool.bumpversion.files]]
# filename = "src/driver.py"